[package]
name = "iota-streams-app-channels"
version = "1.0.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "app", "channels"]
description = "A rust implementation of the IOTA Streams Channels Application"

[features]
default = ["std", "tangle", "sync-client"]
# Enable `std` feature in dependencies
std = ["iota-streams-core/std", "iota-streams-core-edsig/std", "iota-streams-ddml/std", "iota-streams-app/std", "anyhow/std", "hex/std"]
async = ["iota-streams-app/async"]
tangle = ["iota-streams-app/tangle"]
sync-client = ["iota-streams-app/sync-client", "tangle", "std"]
async-client = ["iota-streams-app/async-client", "tangle", "std", "async"]

[lib]
name = "iota_streams_app_channels"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.3.0", path = "../iota-streams-core", default-features = false }
iota-streams-core-edsig = { version = "0.2.0", path = "../iota-streams-core-edsig", default-features = false }
iota-streams-core-keccak = { version = "0.3.0", path = "../iota-streams-core-keccak", default-features = false }
iota-streams-ddml = { version = "0.2.2", path = "../iota-streams-ddml", default-features = false }
iota-streams-app = { version = "1.0.0", path = "../iota-streams-app", default-features = false }
anyhow = { version = "1.0.26", default-features = false }

hex = { version = "0.4.2", default-features = false, optional = false }
